# Generated by Django 3.1.6 on 2021-02-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
